import { useEffect, useMemo, useState } from "react";
import "@/App.css";
import { Bell, ChevronDown, FileText, Filter, LayoutDashboard, LogOut, Menu, Pencil, Plus, Search, Settings, ShieldCheck, Trash2, Users, X, UploadCloud } from "lucide-react";
import { supabase } from "@/lib/supabase";

const avatarImages = [
  "https://images.unsplash.com/photo-1685475887169-9c9a84bf740f?auto=format&fit=crop&w=120&q=80",
  "https://images.unsplash.com/photo-1661263989552-d82526d03b0f?auto=format&fit=crop&w=120&q=80",
];

const seedEmployees = [
  { id: 1, name: "Arjun Mehta", role: "Plant Supervisor", gender: "Male", shift: "Day shift", salary: "₹42,000", absence: "1 day", initials: "AM", avatar: avatarImages[0] },
  { id: 2, name: "Priya Nair", role: "Quality Lead", gender: "Female", shift: "Day shift", salary: "₹38,500", absence: "0 days", initials: "PN", avatar: avatarImages[1] },
  { id: 3, name: "Rakesh Kumar", role: "Line Manager", gender: "Male", shift: "Night shift", salary: "₹35,200", absence: "2 days", initials: "RK" },
  { id: 4, name: "Sneha Desai", role: "Operations Lead", gender: "Female", shift: "Day shift", salary: "₹46,000", absence: "0 days", initials: "SD" },
  { id: 5, name: "Vikram Singh", role: "Maintenance Manager", gender: "Male", shift: "Night shift", salary: "₹41,800", absence: "1 day", initials: "VS" },
];

const seedReports = [
  { id: 1, name: "Safety_Audit_May_2024.pdf", date: "28 May 2024", owner: "Priya Nair", tag: "Safety", access: "Leadership + Admin", size: "2.4 MB" },
  { id: 2, name: "Night_Shift_Absence_Week_21.pdf", date: "24 May 2024", owner: "Rakesh Kumar", tag: "Attendance", access: "Managers", size: "840 KB" },
  { id: 3, name: "Production_Output_May_W4.pdf", date: "31 May 2024", owner: "Arjun Mehta", tag: "Production", access: "All leadership", size: "1.8 MB" },
];

function Login({ onLogin }) {
  const [email, setEmail] = useState("leadership@apexforge.co");
  const [password, setPassword] = useState("password");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const submit = async () => { setError(""); setLoading(true); const result = await onLogin(email, password); if (result?.error) setError(result.error); setLoading(false); };
  return <main className="login-shell">
    <section className="login-visual"><div className="visual-copy"><span className="eyebrow">APEXFORGE / FACTORY OS</span><h1>Run the floor.<br /><em>Know the people.</em></h1><p>One clear view of your workforce, shifts, and the reports that keep production moving.</p><div className="visual-stat"><strong>286</strong><span>active workforce<br /><small>across 3 production units</small></span></div></div></section>
    <section className="login-panel"><div className="login-brand"><span className="brand-mark">AF</span><span>ApexForge <b>OS</b></span></div><div className="login-form"><span className="eyebrow">SECURE ACCESS</span><h2>Welcome back</h2><p className="muted">Sign in to your factory control room.</p><label>Email address<input data-testid="login-email-input" value={email} onChange={e => setEmail(e.target.value)} type="email" /></label><label>Password<div className="password-wrap"><input data-testid="login-password-input" value={password} onChange={e => setPassword(e.target.value)} type="password" /><span>•••</span></div></label><div className="form-row"><label className="check"><input data-testid="login-remember-checkbox" type="checkbox" defaultChecked /> <span>Remember me</span></label><button data-testid="forgot-password-button" className="text-button">Forgot password?</button></div>{error && <p className="login-error" data-testid="login-error-message">{error}</p>}<button data-testid="login-submit-button" className="primary-button login-submit" onClick={submit} disabled={loading}>{loading ? "Signing in…" : "Enter workspace"} <span>→</span></button><p className="login-foot"><ShieldCheck size={14} /> Protected workspace · Supabase session security</p></div><div className="login-footer"><span>© 2024 ApexForge Industries</span><span>Privacy & security</span></div></section>
  </main>;
}

function Modal({ employee, onClose, onSave }) {
  const [form, setForm] = useState(employee || { name: "", role: "", gender: "Male", shift: "Day shift", salary: "", absence: "0 days", initials: "" });
  const update = (key, value) => setForm({ ...form, [key]: value });
  return <div className="modal-backdrop"><div className="modal" data-testid="employee-modal"><div className="modal-head"><div><span className="eyebrow">EMPLOYEE RECORD</span><h2>{employee ? "Edit employee" : "Add employee"}</h2></div><button data-testid="employee-modal-close-button" className="icon-button" onClick={onClose}><X size={18} /></button></div><div className="form-grid"><label>Full name *<input data-testid="employee-name-input" value={form.name} onChange={e => update("name", e.target.value)} placeholder="e.g. Kavita Rao" /></label><label>Role / designation<input data-testid="employee-role-input" value={form.role} onChange={e => update("role", e.target.value)} placeholder="e.g. Line Manager" /></label><label>Gender *<select data-testid="employee-gender-select" value={form.gender} onChange={e => update("gender", e.target.value)}><option>Male</option><option>Female</option><option>Other</option></select></label><label>Shift *<select data-testid="employee-shift-select" value={form.shift} onChange={e => update("shift", e.target.value)}><option>Day shift</option><option>Night shift</option></select></label><label>Monthly salary *<input data-testid="employee-salary-input" value={form.salary} onChange={e => update("salary", e.target.value)} placeholder="₹ 00,000" /></label><label>Absentee record<input data-testid="employee-absence-input" value={form.absence} onChange={e => update("absence", e.target.value)} placeholder="0 days" /></label></div><div className="doc-upload"><div className="upload-icon"><UploadCloud size={19} /></div><div><strong>Identity documents</strong><p>Aadhar or PAN · PDF, JPG up to 5 MB</p></div><button data-testid="employee-document-upload-button" className="outline-button">Choose file</button></div><div className="modal-actions"><button data-testid="employee-cancel-button" className="outline-button" onClick={onClose}>Cancel</button><button data-testid="employee-save-button" className="primary-button" onClick={() => onSave({ ...form, id: form.id || Date.now(), initials: form.name.split(" ").map(n => n[0]).join("").slice(0, 2).toUpperCase() })}>Save employee <span>→</span></button></div></div></div>;
}

function App() {
  const [loggedIn, setLoggedInState] = useState(false);
  const setLoggedIn = (next) => { setLoggedInState(next); if (!next) supabase.auth.signOut(); };
  const [active, setActive] = useState("Overview");
  const [employees, setEmployees] = useState(seedEmployees);
  const [reports, setReports] = useState(seedReports);
  const [search, setSearch] = useState("");
  const [shift, setShift] = useState("All shifts");
  const [modal, setModal] = useState(null);
  const [notice, setNotice] = useState("");
  useEffect(() => { supabase.auth.getSession().then(({ data }) => setLoggedIn(Boolean(data.session))); const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => setLoggedIn(Boolean(session))); return () => listener.subscription.unsubscribe(); }, []);
  const filtered = useMemo(() => employees.filter(e => e.name.toLowerCase().includes(search.toLowerCase()) && (shift === "All shifts" || e.shift === shift)), [employees, search, shift]);
  const saveEmployee = (item) => { setEmployees(current => current.some(e => e.id === item.id) ? current.map(e => e.id === item.id ? item : e) : [item, ...current]); setModal(null); setNotice("Employee record saved"); setTimeout(() => setNotice(""), 2500); };
  const deleteEmployee = (id) => { setEmployees(employees.filter(e => e.id !== id)); setNotice("Employee removed from directory"); setTimeout(() => setNotice(""), 2500); };
  const login = async (email, password) => { const { error } = await supabase.auth.signInWithPassword({ email, password }); return { error: error?.message }; };
  const logout = async () => { await supabase.auth.signOut(); setLoggedIn(false); };
  if (!loggedIn) return <Login onLogin={login} />;
  return <div className="app-shell"><aside className="sidebar"><div className="side-brand"><span className="brand-mark">AF</span><span>ApexForge <b>OS</b></span></div><div className="side-label">OPERATIONS</div><nav>{[["Overview", LayoutDashboard], ["Employees", Users], ["Reports", FileText]].map(([label, Icon]) => <button data-testid={`nav-${label.toLowerCase()}-button`} key={label} className={active === label ? "nav-item active" : "nav-item"} onClick={() => setActive(label)}><Icon size={17} /><span>{label}</span>{label === "Reports" && <small>3</small>}</button>)}</nav><div className="side-label settings-label">WORKSPACE</div><button data-testid="nav-settings-button" className="nav-item"><Settings size={17} /><span>Settings</span></button><div className="side-bottom"><div className="status-dot"><i /> Systems operational</div><div className="profile"><img src={avatarImages[0]} alt="" /><div><strong>Priya Nair</strong><span>Leadership</span></div><ChevronDown size={15} /></div><button data-testid="logout-button" className="logout-button" onClick={() => setLoggedIn(false)}><LogOut size={15} /> Sign out</button></div></aside><main className="main-content"><header className="topbar"><button data-testid="mobile-menu-button" className="mobile-menu"><Menu size={20} /></button><div className="breadcrumb">ApexForge <span>/</span> <b>{active}</b></div><div className="top-actions"><button data-testid="notifications-button" className="icon-button notification"><Bell size={18} /><i /></button><div className="top-profile"><span>PN</span><ChevronDown size={14} /></div></div></header>{active === "Overview" && <Overview onViewEmployees={() => setActive("Employees")} onViewReports={() => setActive("Reports")} />}{active === "Employees" && <Employees employees={filtered} search={search} setSearch={setSearch} shift={shift} setShift={setShift} onAdd={() => setModal({})} onEdit={setModal} onDelete={deleteEmployee} />}{active === "Reports" && <Reports reports={reports} onAdd={() => { setReports([{ id: Date.now(), name: "New_Report_May_2024.pdf", date: "Today", owner: "Priya Nair", tag: "Report", access: "Leadership", size: "Pending" }, ...reports]); setNotice("Report added to repository"); setTimeout(() => setNotice(""), 2500); }} />}{notice && <div className="toast" data-testid="success-notice">{notice}<span>✓</span></div>}{modal && <Modal employee={modal.id ? modal : null} onClose={() => setModal(null)} onSave={saveEmployee} />}</main></div>;
}

function PageHead({ eyebrow, title, children }) { return <div className="page-head"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1></div>{children}</div>; }
function Overview({ onViewEmployees, onViewReports }) { return <div className="page"><PageHead eyebrow="MONDAY · 03 JUNE 2024" title="Good morning, Priya."><button data-testid="overview-add-employee-button" className="primary-button" onClick={onViewEmployees}><Plus size={17} /> Add employee</button></PageHead><section className="hero-band"><div><span className="eyebrow blue">LIVE OPERATIONS</span><h2>Your workforce at a glance.</h2><p>Everything important, in one clear view.</p></div><div className="hero-time"><strong>08:42</strong><span>IST · DAY SHIFT ACTIVE</span></div></section><div className="metric-grid"><Metric label="Active workforce" value="286" change="+4.2%" note="vs. last month" color="blue" /><Metric label="Today’s attendance" value="94.8%" change="+1.8%" note="vs. yesterday" color="green" /><Metric label="On night shift" value="64" change="22.4%" note="of total workforce" color="amber" /><Metric label="Open reports" value="03" change="Needs review" note="2 uploaded today" color="red" /></div><div className="overview-grid"><section className="data-section"><div className="section-head"><div><span className="eyebrow">WORKFORCE</span><h3>Shift attendance</h3></div><button data-testid="overview-view-employees-button" className="text-button" onClick={onViewEmployees}>View directory <span>→</span></button></div><div className="attendance-chart"><div className="chart-y"><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0%</span></div><div className="bars">{[68, 78, 73, 88, 76, 94, 84, 92, 81, 97, 86, 90].map((height, i) => <div className="bar-group" key={i}><div className={`bar ${i > 8 ? "bright" : ""}`} style={{ height: `${height}%` }} title={`${height}%`} /><span>{["M","T","W","T","F","S"][i % 6]}</span></div>)}</div></div></section><section className="data-section alerts"><div className="section-head"><div><span className="eyebrow">ATTENTION NEEDED</span><h3>Latest activity</h3></div><button data-testid="overview-view-reports-button" className="text-button" onClick={onViewReports}>See all <span>→</span></button></div>{[["Report uploaded", "Safety audit · Priya Nair", "12 min ago", "blue"], ["Absence logged", "Rakesh Kumar · Night shift", "1 hr ago", "amber"], ["Employee updated", "Sneha Desai · Salary record", "3 hrs ago", "green"]].map((item, i) => <div className="activity" data-testid={`activity-item-${i}`} key={item[0]}><i className={item[3]} /><div><strong>{item[0]}</strong><span>{item[1]}</span></div><time>{item[2]}</time></div>)}</section></div></div>; }
function Metric({ label, value, change, note, color }) { return <div className="metric" data-testid={`metric-${label.toLowerCase().replaceAll(" ", "-")}`}><div className={`metric-icon ${color}`} /><span className="metric-label">{label}</span><strong>{value}</strong><div><b className={color}>{change}</b><small>{note}</small></div></div>; }
function Employees({ employees, search, setSearch, shift, setShift, onAdd, onEdit, onDelete }) { return <div className="page"><PageHead eyebrow="PEOPLE & ACCESS" title="Employee directory"><button data-testid="add-employee-button" className="primary-button" onClick={onAdd}><Plus size={17} /> Add employee</button></PageHead><div className="directory-toolbar"><div className="search-box"><Search size={17} /><input data-testid="employee-search-input" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search by name or role" /></div><div className="filter-select"><Filter size={15} /><select data-testid="employee-shift-filter" value={shift} onChange={e => setShift(e.target.value)}><option>All shifts</option><option>Day shift</option><option>Night shift</option></select></div><span className="results-count" data-testid="employee-results-count">{employees.length} records</span></div><section className="table-section"><div className="table-caption"><div><span className="eyebrow">DIRECTORY / 2024</span><h3>All employees</h3></div><span className="access-note"><ShieldCheck size={14} /> Salary access: Leadership</span></div><div className="table-wrap"><table><thead><tr><th>Employee</th><th>Gender</th><th>Shift</th><th>Monthly salary</th><th>Absence</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{employees.map(e => <tr data-testid={`employee-row-${e.id}`} key={e.id}><td><div className="person"><div className="avatar">{e.avatar ? <img src={e.avatar} alt="" /> : e.initials}</div><div><strong>{e.name}</strong><span>{e.role}</span></div></div></td><td>{e.gender}</td><td><span className={`shift-pill ${e.shift === "Night shift" ? "night" : "day"}`}><i />{e.shift}</span></td><td className="salary">{e.salary}</td><td>{e.absence}</td><td><div className="row-actions"><button data-testid={`edit-employee-${e.id}-button`} className="icon-button" onClick={() => onEdit(e)}><Pencil size={15} /></button><button data-testid={`delete-employee-${e.id}-button`} className="icon-button danger" onClick={() => onDelete(e.id)}><Trash2 size={15} /></button></div></td></tr>)}</tbody></table>{employees.length === 0 && <div className="empty-state" data-testid="employees-empty-state">No employees match your search.</div>}</div></section></div>; }
function Reports({ reports, onAdd }) { const [activeTag, setActiveTag] = useState("All reports"); const tags = ["All reports", "Safety", "Attendance", "Production", "Compliance"]; const visibleReports = activeTag === "All reports" ? reports : reports.filter(report => report.tag === activeTag); return <div className="page"><PageHead eyebrow="DOCUMENT REPOSITORY" title="Reports"><button data-testid="upload-report-button" className="primary-button" onClick={onAdd}><UploadCloud size={17} /> Upload report</button></PageHead><section className="report-intro"><div><span className="eyebrow">FILE NAMING STANDARD</span><h2>Keep every report findable.</h2><p>Use <b>ReportName_Date</b> when uploading. Tags and access rules are saved with every document.</p></div><div className="report-rule"><FileText size={20} /><span>PDF, DOCX, XLSX<br /><b>Max 25 MB per file</b></span></div></section><div className="tag-row"><span className="eyebrow">FILTER BY TAG</span>{tags.map(tag => <button data-testid={`report-tag-${tag.toLowerCase().replace(" ", "-")}-button`} className={activeTag === tag ? "tag active" : "tag"} key={tag} onClick={() => setActiveTag(tag)}>{tag}</button>)}</div><section className="table-section report-table"><div className="table-caption"><div><span className="eyebrow">REPOSITORY / {visibleReports.length.toString().padStart(2, "0")} FILES</span><h3>Recent reports</h3></div><span className="access-note"><ShieldCheck size={14} /> Role-based access enabled</span></div><div className="table-wrap"><table><thead><tr><th>Document</th><th>Tag</th><th>Uploaded</th><th>Access</th><th>Size</th><th /></tr></thead><tbody>{visibleReports.map(r => <tr data-testid={`report-row-${r.id}`} key={r.id}><td><div className="document"><div className="file-icon"><FileText size={17} /></div><div><strong>{r.name}</strong><span>Uploaded by {r.owner}</span></div></div></td><td><span className="report-tag">{r.tag}</span></td><td>{r.date}</td><td>{r.access}</td><td>{r.size}</td><td><button data-testid={`download-report-${r.id}-button`} className="text-button">Open <span>↗</span></button></td></tr>)}</tbody></table>{visibleReports.length === 0 && <div className="empty-state" data-testid="reports-empty-state">No reports have this tag yet.</div>}</div></section></div>; }

export default App;
